"""
Minimal ICC v4 matrix/TRC profile builder for a linear ProPhoto RGB working space.

trichrom's merged TIFFs are linear (no gamma curve applied anywhere) and use each
sensor channel's own response directly (unity white balance, no color matrix) — so
the embedded profile just needs to say "these are ProPhoto-primaries RGB numbers,
read linearly." ProPhoto is wide enough to hold every real color the sensor can
report without clipping the gamut.
"""

import struct
import time

import numpy as np

PROPHOTO_PRIMARIES = {
    'r': (0.734699, 0.265301),
    'g': (0.159597, 0.840403),
    'b': (0.036598, 0.000105),
}
PROPHOTO_WHITE = (0.3457, 0.3585)  # D50 — ProPhoto's native white point, no adaptation needed
D50_XYZ = (0.9642, 1.0, 0.8249)


def _primary_xyz(xy):
    x, y = xy
    return np.array([x / y, 1.0, (1 - x - y) / y])


def _rgb_to_xyz_matrix(primaries, white_xy):
    """Standard primaries+white-point -> RGB-to-XYZ matrix derivation."""
    p = np.stack([_primary_xyz(primaries[c]) for c in 'rgb'], axis=1)
    w = _primary_xyz(white_xy)
    s = np.linalg.solve(p, w)
    return p * s


def _pad4(data):
    return data + b'\x00' * ((-len(data)) % 4)


def _s15fixed16(value):
    return struct.pack('>i', round(value * 65536))


def _xyz_type(xyz):
    return _pad4(b'XYZ ' + b'\x00' * 4 + b''.join(_s15fixed16(v) for v in xyz))


def _curv_linear():
    """curveType with a zero-entry table means the identity curve y=x (ICC spec)."""
    return b'curv' + struct.pack('>II', 0, 0)


def _mluc(text):
    body = text.encode('utf-16-be')
    header = b'mluc' + struct.pack('>III', 0, 1, 12)
    record = b'enUS' + struct.pack('>II', len(body), 16 + 12)
    return _pad4(header + record + body)


def build_linear_prophoto_icc():
    """Build a matrix/TRC ICC profile: ProPhoto RGB primaries, D50 white, linear TRC."""
    matrix = _rgb_to_xyz_matrix(PROPHOTO_PRIMARIES, PROPHOTO_WHITE)

    tags = {
        'desc': _mluc('Linear ProPhoto RGB'),
        'cprt': _mluc('No copyright, generated by trichrom'),
        'wtpt': _xyz_type(D50_XYZ),
        'rXYZ': _xyz_type(matrix[:, 0]),
        'gXYZ': _xyz_type(matrix[:, 1]),
        'bXYZ': _xyz_type(matrix[:, 2]),
        'rTRC': _curv_linear(),
        'gTRC': _curv_linear(),
        'bTRC': _curv_linear(),
    }

    header_size = 128
    table_size = 4 + 12 * len(tags)
    offset = header_size + table_size

    entries = []
    blob = b''
    for sig, data in tags.items():
        entries.append((sig, offset, len(data)))
        blob += data
        offset += len(data)

    tag_table = struct.pack('>I', len(tags))
    for sig, off, size in entries:
        tag_table += sig.encode('ascii') + struct.pack('>II', off, size)

    total_size = header_size + len(tag_table) + len(blob)

    t = time.gmtime()
    header = b''.join([
        struct.pack('>I', total_size),
        b'\x00\x00\x00\x00',                       # CMM type
        struct.pack('>I', 0x04300000),              # profile version 4.3.0.0
        b'mntr',                                    # device class: display
        b'RGB ',                                     # data colour space
        b'XYZ ',                                     # PCS
        struct.pack('>6H', t.tm_year, t.tm_mon, t.tm_mday, t.tm_hour, t.tm_min, t.tm_sec),
        b'acsp',
        b'\x00\x00\x00\x00',                        # primary platform
        struct.pack('>I', 0),                        # flags
        b'\x00\x00\x00\x00',                        # device manufacturer
        b'\x00\x00\x00\x00',                        # device model
        b'\x00' * 8,                                 # device attributes
        struct.pack('>I', 0),                        # rendering intent: perceptual
        _s15fixed16(D50_XYZ[0]), _s15fixed16(D50_XYZ[1]), _s15fixed16(D50_XYZ[2]),
        b'\x00\x00\x00\x00',                        # profile creator
        b'\x00' * 16,                                # profile ID
        b'\x00' * 28,                                # reserved
    ])
    assert len(header) == header_size

    return header + tag_table + blob
